export const LOAD_ALL_FLIGHTS = 'LOAD_ALL_FLIGHTS';
export const LOAD_ALL_FLIGHTS_ASYNC = 'LOAD_ALL_FLIGHTS_ASYNC';
export const FILTER_FLIGHTS = 'FILTER_FLIGHTS';
export const FILTERED_FLIGHTS = 'FILTERED_FLIGHTS';
